### ISSUE TITLE
Dica

### ISSUE THREAD

**Issue by EufranioDiogo** [vcwild/customscripts#2]
Mano vi o seu código do jogo e farei um fork, mas te aconselharia a colocares todos os módulos como o room, item e todos os outros dentro do dir main por que facilita na hora da execução, por que quando eu fiz o clone do seu repositório, entrei para o main e fiz a execução do main.py e deu erro por que vc estava importando classes que estavam dentro dos módulos que estavam em um dir acima do dir que o main.py estava, para resolver tive de colocar o main.py no mesmo dir que os outros e só assim executou! :+1:

**Comment by vcwild** [comment]
Boa tarde @EufranioDiogo, concordo que está invertido (main deveria estar no root e os módulos em libs, não o contrário). Eu acabei deixando porque empacotei o projeto meio que no improviso, mas ainda assim estava funcionando normalmente. Vou verificar esse erro, obrigado!

**Comment by vcwild** [comment]
@EufranioDiogo atualizei a biblioteca no formato de pacotes, peço que teste e verifique. Se encontrar algum erro sinta-se à vontade para abrir uma nova issue.

**Comment by EufranioDiogo** [comment]
> @EufranioDiogo atualizei a biblioteca no formato de pacotes, peço que teste e verifique. Se encontrar algum erro sinta-se à vontade para abrir uma nova issue.


Verifiquei e está funcionando, abraçam mano!

Uhm e algo que esqueci de dizer, o seu jogo é legal :vulcan_salute: 
:+1:
